// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package content

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func About() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main id=\"content\" role=\"main\"><!-- Hero Section --><div class=\"container space-top-3 space-top-lg-4\"><!-- Title --><div class=\"w-lg-65 text-center mx-lg-auto mb-5 mb-md-9\"><h1>About Paylary</h1></div><!-- End Title --><div class=\"row\"><div class=\"col-md-7\"><div class=\"ml-lg-4\"></div></div></div></div><!-- End Hero Section --><!-- Services Section --><div class=\"container space-1 space-lg-1\"><!-- Title --><div class=\"w-md-80 w-lg-60 text-center mx-md-auto mb-9\"><span class=\"d-block small font-weight-bold text-cap mb-2\">What we do</span><h2>Based on the concept of Web 3.0, Paylary creates a modern secure crypto infrastructure with wide functionality.</h2></div><!-- End Title --><div class=\"container content-space-2 content-space-lg-3\"><div class=\"row justify-content-lg-between\"><div class=\"col-lg-4 mb-5 mb-lg-0\"><h2>Tools should adapt to the user, not the other way around.</h2></div><!-- End Col --><div class=\"col-lg-6\"><p>Paylary is the future of crypto financial services encompassing a secure communication, advanced crypto wallet, payments, debit card, NFT in a one functional app.</p><p>Things can get really complex, really quickly, and a pragmatic, synthetic and clear vision is essential to be able to create something that, after all, is meant to be used. Emotions also have a big role to play and developing.</p></div><!-- End Col --></div><!-- End Row --></div></div><!-- End Services Section --><!-- Services Section --><!-- End Services Section --><!-- Clients Section --><!-- End Clients Section --></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
