// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package content

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login(err string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- ========== MAIN ========== --><main id=\"content\" role=\"main\"><!-- Login Form --><div class=\"container space-2 space-lg-3\"><form class=\"js-validate w-md-75 w-lg-50 mx-md-auto\" action=\"/login\" method=\"post\"><!-- Title --><div class=\"mb-5 mb-md-7\"><h1 class=\"h2 mb-0\">Welcome back</h1><p><a href=\"/\">Back to main page </a></p></div><!-- End Title --><!-- Form Group --><div class=\"js-form-message form-group\"><label class=\"input-label\" for=\"signinSrEmail\">Email address</label> <input type=\"email\" class=\"form-control\" name=\"email\" id=\"signinSrEmail\" placeholder=\"Email address\" aria-label=\"Email address\" required data-msg=\"Please enter a valid email address.\"></div><!-- End Form Group --><!-- Form Group --><div class=\"js-form-message form-group\"><label class=\"input-label\" for=\"signinSrPassword\"><span class=\"d-flex justify-content-between align-items-center\">Password <a class=\"link-underline text-capitalize font-weight-normal\" href=\"/recover\">Forgot Password?</a></span></label> <input type=\"password\" class=\"form-control\" name=\"password\" id=\"signinSrPassword\" placeholder=\"********\" aria-label=\"********\" required data-msg=\"Your password is invalid. Please try again.\"></div><!-- End Form Group --><!-- Button --><div class=\"row align-items-center mb-5\"><div class=\"col-sm-6 mb-3 mb-sm-0\"><span class=\"font-size-1 text-muted\">Don't have an account?</span> <a class=\"font-size-1 font-weight-bold\" href=\"/signup\">Signup</a></div><div class=\"col-sm-6 text-sm-right\"><button type=\"submit\" class=\"btn btn-primary transition-3d-hover\">Sign In</button></div></div><!-- End Button -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if err != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-danger\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(err)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/content/login.templ`, Line: 53, Col: 39}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form></div><!-- End Login Form --></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
